/* MIT License
 *
 * Copyright (c) The c-ares project and its contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * SPDX-License-Identifier: MIT
 */
#include "ares-test.h"
#include "dns-proto.h"

extern "C" {
// Remove command-line defines of package variables for the test project...
#undef PACKAGE_NAME
#undef PACKAGE_BUGREPORT
#undef PACKAGE_STRING
#undef PACKAGE_TARNAME
// ... so we can include the library's config without symbol redefinitions.
#include "ares_private.h"
}

#ifndef CARES_SYMBOL_HIDING

extern "C" {
#  include "dnssec/ares_dnssec.h"
#  include "dnssec/ares_dnssec_int.h"
#  include "record/ares_dns_private.h"
}

#  include <string>
#  include <vector>

#  ifdef CARES_TEST_OPENSSL
#    include <openssl/evp.h>
#    include <openssl/x509.h>
#    include <openssl/err.h>
#  endif

// Test vectors, generated by ares-test-dnssec-vectors.py
#  include "ares-test-dnssec-vectors.h"

using testing::_;

namespace ares {
namespace test {

static std::vector<unsigned char> Base64Decode(const std::string &in)
{
  std::vector<unsigned char> out;
  unsigned int               acc   = 0;
  int                        nbits = 0;
  for (char c : in) {
    int val;
    if (c >= 'A' && c <= 'Z') {
      val = c - 'A';
    } else if (c >= 'a' && c <= 'z') {
      val = c - 'a' + 26;
    } else if (c >= '0' && c <= '9') {
      val = c - '0' + 52;
    } else if (c == '+') {
      val = 62;
    } else if (c == '/') {
      val = 63;
    } else {
      continue; /* padding */
    }
    acc    = (acc << 6) | (unsigned int)val;
    nbits += 6;
    if (nbits >= 8) {
      nbits -= 8;
      out.push_back((unsigned char)(acc >> nbits));
    }
  }
  return out;
}

static std::vector<unsigned char> Pieces(const char * const *pieces)
{
  std::string b64;
  for (; *pieces; pieces++) {
    b64 += *pieces;
  }
  return Base64Decode(b64);
}

/*
 * Crypto functions for the tests.  c-ares has no cryptography, applications
 * provide it.  The tests use OpenSSL when available.
 */

#  ifdef CARES_TEST_OPENSSL

#    if defined(EVP_PKEY_ED25519) &&        \
      (!defined(LIBRESSL_VERSION_NUMBER) || \
       (LIBRESSL_VERSION_NUMBER >= 0x3070000fL))
#      define TEST_HAVE_ED25519
#    endif
#    if defined(EVP_PKEY_ED448) && !defined(LIBRESSL_VERSION_NUMBER) && \
      !defined(OPENSSL_IS_BORINGSSL) && !defined(OPENSSL_IS_AWSLC)
#      define TEST_HAVE_ED448
#    endif

typedef std::vector<unsigned char> Bytes;

static void DerLen(Bytes *out, size_t len)
{
  if (len < 0x80) {
    out->push_back((unsigned char)len);
  } else if (len < 0x100) {
    out->push_back(0x81);
    out->push_back((unsigned char)len);
  } else {
    out->push_back(0x82);
    out->push_back((unsigned char)(len >> 8));
    out->push_back((unsigned char)len);
  }
}

static Bytes DerTag(unsigned char tag, const Bytes &content)
{
  Bytes out;
  out.push_back(tag);
  DerLen(&out, content.size());
  out.insert(out.end(), content.begin(), content.end());
  return out;
}

// A DER INTEGER with an unsigned big-endian value
static Bytes DerUint(const unsigned char *num, size_t len)
{
  while (len > 1 && num[0] == 0) {
    num++;
    len--;
  }
  Bytes content;
  if (len && (num[0] & 0x80)) {
    content.push_back(0);
  }
  content.insert(content.end(), num, num + len);
  return DerTag(0x02, content);
}

// SubjectPublicKeyInfo of a DNSSEC public key.  c-ares has checked the
// format and size of the key.
static Bytes Spki(unsigned char alg, const unsigned char *key, size_t keylen)
{
  static const unsigned char p256[]    = { 0x30, 0x59, 0x30, 0x13, 0x06, 0x07,
                                           0x2a, 0x86, 0x48, 0xce, 0x3d, 0x02,
                                           0x01, 0x06, 0x08, 0x2a, 0x86, 0x48,
                                           0xce, 0x3d, 0x03, 0x01, 0x07, 0x03,
                                           0x42, 0x00, 0x04 };
  static const unsigned char p384[]    = { 0x30, 0x76, 0x30, 0x10, 0x06, 0x07,
                                           0x2a, 0x86, 0x48, 0xce, 0x3d, 0x02,
                                           0x01, 0x06, 0x05, 0x2b, 0x81, 0x04,
                                           0x00, 0x22, 0x03, 0x62, 0x00, 0x04 };
  static const unsigned char ed25519[] = { 0x30, 0x2a, 0x30, 0x05, 0x06, 0x03,
                                           0x2b, 0x65, 0x70, 0x03, 0x21, 0x00 };
  static const unsigned char ed448[]   = { 0x30, 0x43, 0x30, 0x05, 0x06, 0x03,
                                           0x2b, 0x65, 0x71, 0x03, 0x3a, 0x00 };
  // AlgorithmIdentifier for rsaEncryption, with NULL parameters
  static const unsigned char rsa[]  = { 0x30, 0x0d, 0x06, 0x09, 0x2a,
                                        0x86, 0x48, 0x86, 0xf7, 0x0d,
                                        0x01, 0x01, 0x01, 0x05, 0x00 };
  const unsigned char       *prefix = nullptr;
  size_t                     plen   = 0;
  switch (alg) {
    case 13:
      prefix = p256;
      plen   = sizeof(p256);
      break;
    case 14:
      prefix = p384;
      plen   = sizeof(p384);
      break;
    case 15:
      prefix = ed25519;
      plen   = sizeof(ed25519);
      break;
    case 16:
      prefix = ed448;
      plen   = sizeof(ed448);
      break;
    default:
      break;
  }
  if (prefix != nullptr) {
    Bytes out(prefix, prefix + plen);
    out.insert(out.end(), key, key + keylen);
    return out;
  }

  // RSA, RFC 3110 section 2
  size_t explen;
  size_t expoff;
  if (key[0] != 0) {
    explen = key[0];
    expoff = 1;
  } else {
    explen = ((size_t)key[1] << 8) | key[2];
    expoff = 3;
  }
  Bytes seq = DerUint(key + expoff + explen, keylen - expoff - explen);
  Bytes exp = DerUint(key + expoff, explen);
  seq.insert(seq.end(), exp.begin(), exp.end());
  Bytes bits(1, 0);
  Bytes rsakey = DerTag(0x30, seq);
  bits.insert(bits.end(), rsakey.begin(), rsakey.end());
  Bytes spki(rsa, rsa + sizeof(rsa));
  Bytes bitstr = DerTag(0x03, bits);
  spki.insert(spki.end(), bitstr.begin(), bitstr.end());
  return DerTag(0x30, spki);
}

static ares_bool_t TestAlgSupported(unsigned char alg, void *user_data)
{
  (void)user_data;
  switch (alg) {
    case 5:
    case 7:
    case 8:
    case 10:
    case 13:
    case 14:
#    ifdef TEST_HAVE_ED25519
    case 15:
#    endif
#    ifdef TEST_HAVE_ED448
    case 16:
#    endif
      return ARES_TRUE;
    default:
      return ARES_FALSE;
  }
}

static ares_status_t TestVerify(unsigned char alg, const unsigned char *key,
                                size_t key_len, const unsigned char *data,
                                size_t data_len, const unsigned char *sig,
                                size_t sig_len, void *user_data)
{
  const EVP_MD *md      = nullptr;
  bool          oneshot = false;
  Bytes         dersig(sig, sig + sig_len);
  ares_status_t status = ARES_EBADRESP;

  (void)user_data;
  switch (alg) {
    case 5:
    case 7:
      md = EVP_sha1();
      break;
    case 8:
    case 13:
      md = EVP_sha256();
      break;
    case 10:
      md = EVP_sha512();
      break;
    case 14:
      md = EVP_sha384();
      break;
    default:
      oneshot = true;
      break;
  }
  if (alg == 13 || alg == 14) {
    // RFC 6605 section 4: r | s, to ECDSA-Sig-Value
    Bytes seq = DerUint(sig, sig_len / 2);
    Bytes s2  = DerUint(sig + sig_len / 2, sig_len / 2);
    seq.insert(seq.end(), s2.begin(), s2.end());
    dersig = DerTag(0x30, seq);
  }

  Bytes                der   = Spki(alg, key, key_len);
  const unsigned char *p     = der.data();
  EVP_PKEY            *pkey  = d2i_PUBKEY(nullptr, &p, (long)der.size());
  EVP_MD_CTX          *mdctx = EVP_MD_CTX_new();
  if (pkey != nullptr && mdctx != nullptr &&
      EVP_DigestVerifyInit(mdctx, nullptr, md, nullptr, pkey) == 1) {
    int rc;
    if (oneshot) {
      rc =
        EVP_DigestVerify(mdctx, dersig.data(), dersig.size(), data, data_len);
    } else {
      rc = (EVP_DigestVerifyUpdate(mdctx, data, data_len) == 1)
             ? EVP_DigestVerifyFinal(mdctx, dersig.data(), dersig.size())
             : 0;
    }
    if (rc == 1) {
      status = ARES_SUCCESS;
    }
  }
  EVP_MD_CTX_free(mdctx);
  EVP_PKEY_free(pkey);
  ERR_clear_error();
  return status;
}

static const EVP_MD *DigestMd(unsigned char digest_type)
{
  switch (digest_type) {
    case 1:
      return EVP_sha1();
    case 2:
      return EVP_sha256();
    case 4:
      return EVP_sha384();
    default:
      return nullptr;
  }
}

static ares_bool_t TestDigestSupported(unsigned char digest_type,
                                       void         *user_data)
{
  (void)user_data;
  return DigestMd(digest_type) != nullptr ? ARES_TRUE : ARES_FALSE;
}

static ares_status_t TestDigest(unsigned char        digest_type,
                                const unsigned char *data, size_t data_len,
                                unsigned char *out, size_t *out_len,
                                void *user_data)
{
  const EVP_MD *md  = DigestMd(digest_type);
  unsigned int  len = 0;
  (void)user_data;
  if (md == nullptr || *out_len < (size_t)EVP_MD_size(md) ||
      EVP_Digest(data, data_len, out, &len, md, nullptr) != 1) {
    return ARES_EFORMERR;
  }
  *out_len = len;
  return ARES_SUCCESS;
}

static const ares_dnssec_crypto_t test_crypto = { TestAlgSupported, TestVerify,
                                                  TestDigestSupported,
                                                  TestDigest, nullptr };

// The crypto functions for the tests, NULL when there are none
static const ares_dnssec_crypto_t *TestCrypto()
{
  return &test_crypto;
}

#  else

static const ares_dnssec_crypto_t *TestCrypto()
{
  return nullptr;
}

#  endif

static ares_bool_t NoAlgSupported(unsigned char alg, void *user_data)
{
  (void)alg;
  (void)user_data;
  return ARES_FALSE;
}

static ares_status_t NoVerify(unsigned char alg, const unsigned char *key,
                              size_t key_len, const unsigned char *data,
                              size_t data_len, const unsigned char *sig,
                              size_t sig_len, void *user_data)
{
  (void)alg;
  (void)key;
  (void)key_len;
  (void)data;
  (void)data_len;
  (void)sig;
  (void)sig_len;
  (void)user_data;
  return ARES_ENOTIMP;
}

static ares_status_t NoDigest(unsigned char        digest_type,
                              const unsigned char *data, size_t data_len,
                              unsigned char *out, size_t *out_len,
                              void *user_data)
{
  (void)digest_type;
  (void)data;
  (void)data_len;
  (void)out;
  (void)out_len;
  (void)user_data;
  return ARES_ENOTIMP;
}

// Crypto functions that support nothing, for tests without cryptography
static const ares_dnssec_crypto_t no_crypto = { NoAlgSupported, NoVerify,
                                                NoAlgSupported, NoDigest,
                                                nullptr };

#  define REQUIRE_CRYPTO()                                     \
    do {                                                       \
      if (TestCrypto() == nullptr) {                           \
        GTEST_SKIP() << "no crypto functions (needs OpenSSL)"; \
      }                                                        \
    } while (0)

static bool ParseName(const char *str, unsigned char *wire)
{
  return ares_dnssec_name_parse(str, strlen(str), wire) == ARES_SUCCESS;
}

static std::string BufStr(ares_buf_t *buf)
{
  size_t               len = 0;
  const unsigned char *ptr = ares_buf_peek(buf, &len);
  return std::string((const char *)ptr, len);
}

/*
 * Building blocks: names, messages, canonical form, key tags, digests,
 * signatures and NSEC3 hashes
 */

TEST_F(LibraryTest, DNSSECNames)
{
  unsigned char             a[DNSSEC_NAME_MAX];
  unsigned char             b[DNSSEC_NAME_MAX];
  char                      str[ARES_DNSSEC_NAME_STRLEN];
  // RFC 4034 section 6.1, in canonical order
  static const char * const order[] = {
    "example.",         "a.example.",      "yljkjljk.a.example.",
    "Z.a.example.",     "zABC.a.EXAMPLE.", "z.example.",
    "\\001.z.example.", "*.z.example.",    "\\200.z.example."
  };
  static const char * const bad[] = { "",      "..",     "a..b.", ".a.",
                                      "a.b..", "\\256.", "\\25",  "a\\" };

  ASSERT_TRUE(ParseName("www.Example.COM", a));
  EXPECT_EQ(17u, ares_dnssec_name_len(a));
  EXPECT_EQ(3u, ares_dnssec_name_labels(a));
  ares_dnssec_name_str(a, str, sizeof(str));
  EXPECT_STREQ("www.Example.COM.", str);
  ASSERT_TRUE(ParseName("www.example.com.", b));
  EXPECT_TRUE(ares_dnssec_name_eq(a, b));
  EXPECT_EQ(0, ares_dnssec_name_cmp(a, b));

  ASSERT_TRUE(ParseName(".", a));
  EXPECT_EQ(0, a[0]);
  ares_dnssec_name_str(a, str, sizeof(str));
  EXPECT_STREQ(".", str);

  // escapes
  ASSERT_TRUE(ParseName("a\\.b.\\065\\\\c.", a));
  EXPECT_EQ(3, a[0]);
  EXPECT_EQ(0, memcmp(&a[1], "a.b", 3));
  EXPECT_EQ(3, a[4]);
  EXPECT_EQ(0, memcmp(&a[5], "A\\c", 3));
  ares_dnssec_name_str(a, str, sizeof(str));
  EXPECT_STREQ("a\\046b.A\\092c.", str);

  for (const char *name : bad) {
    EXPECT_FALSE(ParseName(name, a)) << name;
  }

  std::string label63(63, 'a');
  EXPECT_TRUE(ParseName(label63.c_str(), a));
  std::string label64(64, 'a');
  EXPECT_FALSE(ParseName(label64.c_str(), a));
  // 127 labels of one octet is 255 octets with the root
  std::string longname;
  for (int i = 0; i < 127; i++) {
    longname += "a.";
  }
  EXPECT_TRUE(ParseName(longname.c_str(), a));
  EXPECT_EQ(127u, ares_dnssec_name_labels(a));
  longname += "a.";
  EXPECT_FALSE(ParseName(longname.c_str(), a));

  for (size_t i = 1; i < sizeof(order) / sizeof(order[0]); i++) {
    ASSERT_TRUE(ParseName(order[i - 1], a));
    ASSERT_TRUE(ParseName(order[i], b));
    EXPECT_LT(ares_dnssec_name_cmp(a, b), 0) << order[i - 1];
    EXPECT_GT(ares_dnssec_name_cmp(b, a), 0) << order[i];
  }

  ASSERT_TRUE(ParseName("x.y.Example.", a));
  ASSERT_TRUE(ParseName("example.", b));
  EXPECT_TRUE(ares_dnssec_name_sub(a, b));
  EXPECT_TRUE(ares_dnssec_name_sub(a, a));
  EXPECT_FALSE(ares_dnssec_name_sub(b, a));
  EXPECT_EQ(1u, ares_dnssec_name_common(a, b));
  EXPECT_TRUE(ares_dnssec_name_eq(ares_dnssec_name_suffix(a, 1), b));
  ASSERT_TRUE(ParseName("*.a.example.", a));
  EXPECT_EQ(2u, ares_dnssec_name_sig_labels(a));
  ASSERT_TRUE(ParseName("xexample.", a));
  EXPECT_FALSE(ares_dnssec_name_sub(a, b));
}

// A response with compressed names: example.com. IN MX, one MX record
// "10 MAIL.example.com." with the RDATA name compressed
static const unsigned char dnssec_mx[] = {
  0x12, 0x34, 0x81, 0x80, 0x00, 0x01, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00,
  // question at 12: example.com. MX IN
  0x07, 'e', 'x', 'a', 'm', 'p', 'l', 'e', 0x03, 'c', 'o', 'm', 0x00, 0x00,
  0x0f, 0x00, 0x01,
  // answer: EXAMPLE.com (pointer to "com" at 20) MX IN TTL 3600
  0x07, 'E', 'X', 'A', 'M', 'P', 'L', 'E', 0xc0, 0x14, 0x00, 0x0f, 0x00, 0x01,
  0x00, 0x00, 0x0e, 0x10, 0x00, 0x09, 0x00, 0x0a, 0x04, 'M', 'A', 'I', 'L',
  0xc0, 0x0c,
  // answer: pointer to the question name, NSEC to "A.example.com."
  0xc0, 0x0c, 0x00, 0x2f, 0x00, 0x01, 0x00, 0x00, 0x0e, 0x10, 0x00, 0x12, 0x01,
  'A', 0x07, 'e', 'x', 'a', 'm', 'p', 'l', 'e', 0x03, 'c', 'o', 'm', 0x00, 0x00,
  0x01, 0x40
};

TEST_F(LibraryTest, DNSSECMessages)
{
  struct dnssec_msg *m = NULL;
  unsigned char      name[DNSSEC_NAME_MAX];
  unsigned char      bad[sizeof(dnssec_mx)];
  ares_bool_t        badmap;

  ASSERT_EQ(ARES_SUCCESS,
            ares_dnssec_msg_parse(dnssec_mx, sizeof(dnssec_mx), &m));
  ASSERT_NE(nullptr, m);
  EXPECT_EQ(2u, m->nrrs);
  EXPECT_EQ(15, m->qtype);
  ASSERT_TRUE(ParseName("example.com.", name));
  EXPECT_TRUE(ares_dnssec_name_eq(DNSSEC_RR_OWNER(m, &m->rrs[0]), name));
  EXPECT_TRUE(ares_dnssec_name_eq(DNSSEC_RR_OWNER(m, &m->rrs[1]), name));

  // MX: the name is expanded and lowercased
  ares_buf_t *out = ares_buf_create();
  ASSERT_NE(nullptr, out);
  EXPECT_EQ(ARES_SUCCESS, ares_dnssec_rdata_canonical(m, &m->rrs[0], out));
  EXPECT_EQ(std::string("\x00\x0a\x04mail\x07"
                        "example\x03"
                        "com\x00",
                        20),
            BufStr(out));
  ares_buf_destroy(out);
  // NSEC: the next name keeps its case (RFC 6840 5.1)
  out = ares_buf_create();
  ASSERT_NE(nullptr, out);
  EXPECT_EQ(ARES_SUCCESS, ares_dnssec_rdata_canonical(m, &m->rrs[1], out));
  EXPECT_EQ(18u, ares_buf_len(out));
  EXPECT_EQ(std::string("\x01"
                        "A"),
            BufStr(out).substr(0, 2));
  ares_buf_destroy(out);
  EXPECT_TRUE(ares_dnssec_bitmap_has(DNSSEC_RR_RDATA(m, &m->rrs[1]) + 15, 3,
                                     DNSSEC_TYPE_A, &badmap));
  EXPECT_FALSE(badmap);
  ares_dnssec_msg_free(m);
  m = NULL;

  // a compression pointer pointing forward
  memcpy(bad, dnssec_mx, sizeof(bad));
  bad[38] = 0x30;
  EXPECT_NE(ARES_SUCCESS, ares_dnssec_msg_parse(bad, sizeof(bad), &m));
  EXPECT_EQ(nullptr, m);
  // a pointer to itself
  memcpy(bad, dnssec_mx, sizeof(bad));
  bad[59] = 0x3a;
  EXPECT_NE(ARES_SUCCESS, ares_dnssec_msg_parse(bad, sizeof(bad), &m));
  EXPECT_EQ(nullptr, m);
  // truncated (TC)
  memcpy(bad, dnssec_mx, sizeof(bad));
  bad[2] |= 0x02;
  EXPECT_NE(ARES_SUCCESS, ares_dnssec_msg_parse(bad, sizeof(bad), &m));
  EXPECT_EQ(nullptr, m);
  // a query, not a response
  memcpy(bad, dnssec_mx, sizeof(bad));
  bad[2] &= 0x7f;
  EXPECT_NE(ARES_SUCCESS, ares_dnssec_msg_parse(bad, sizeof(bad), &m));
  EXPECT_EQ(nullptr, m);
  // cut short
  EXPECT_NE(ARES_SUCCESS,
            ares_dnssec_msg_parse(dnssec_mx, sizeof(dnssec_mx) - 1, &m));
  EXPECT_EQ(nullptr, m);
  // more records than can fit
  memcpy(bad, dnssec_mx, sizeof(bad));
  bad[7] = 0xff;
  EXPECT_NE(ARES_SUCCESS, ares_dnssec_msg_parse(bad, sizeof(bad), &m));
  EXPECT_EQ(nullptr, m);
}

TEST_F(LibraryTest, DNSSECBitmaps)
{
  // RFC 4034 section 4.3: A MX RRSIG NSEC TYPE1234
  static const unsigned char map[] = { 0x00, 0x06, 0x40, 0x01, 0x00, 0x00, 0x00,
                                       0x03, 0x04, 0x1b, 0x00, 0x00, 0x00, 0x00,
                                       0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                       0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                       0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                       0x00, 0x20 };
  static const unsigned char unordered[] = {
    0x01, 0x01, 0x80, 0x00, 0x01, 0x40
  };
  static const unsigned char empty[]   = { 0x00, 0x00 };
  static const unsigned char toolong[] = { 0x00, 0x05, 0x40 };
  ares_bool_t                bad;

  EXPECT_TRUE(ares_dnssec_bitmap_has(map, sizeof(map), 1, &bad));
  EXPECT_FALSE(bad);
  EXPECT_TRUE(ares_dnssec_bitmap_has(map, sizeof(map), 15, &bad));
  EXPECT_TRUE(ares_dnssec_bitmap_has(map, sizeof(map), 46, &bad));
  EXPECT_TRUE(ares_dnssec_bitmap_has(map, sizeof(map), 47, &bad));
  EXPECT_TRUE(ares_dnssec_bitmap_has(map, sizeof(map), 1234, &bad));
  EXPECT_FALSE(ares_dnssec_bitmap_has(map, sizeof(map), 2, &bad));
  EXPECT_FALSE(ares_dnssec_bitmap_has(map, sizeof(map), 1235, &bad));
  EXPECT_FALSE(ares_dnssec_bitmap_has(map, sizeof(map), 65535, &bad));
  EXPECT_FALSE(ares_dnssec_bitmap_has(map, 0, 1, &bad));
  EXPECT_FALSE(bad);
  (void)ares_dnssec_bitmap_has(unordered, sizeof(unordered), 1, &bad);
  EXPECT_TRUE(bad);
  (void)ares_dnssec_bitmap_has(empty, sizeof(empty), 1, &bad);
  EXPECT_TRUE(bad);
  (void)ares_dnssec_bitmap_has(toolong, sizeof(toolong), 1, &bad);
  EXPECT_TRUE(bad);
}

TEST_F(LibraryTest, DNSSECDigests)
{
  REQUIRE_CRYPTO();
  for (const struct dv_ds &t : dv_ds) {
    unsigned char              owner[DNSSEC_NAME_MAX];
    unsigned char              digest[DNSSEC_DIGEST_MAX];
    std::vector<unsigned char> key = Base64Decode(t.dnskey);
    ASSERT_TRUE(ParseName(t.owner, owner));
    EXPECT_EQ(t.keytag, ares_dnssec_keytag(key.data(), key.size())) << t.owner;
    size_t      dlen = ares_dnssec_digest(TestCrypto(), (unsigned char)t.dtype,
                                          owner, ares_dnssec_name_len(owner),
                                          key.data(), key.size(), digest);
    std::string hex;
    for (size_t j = 0; j < dlen; j++) {
      static const char digits[]  = "0123456789abcdef";
      hex                        += digits[digest[j] >> 4];
      hex                        += digits[digest[j] & 0x0f];
    }
    EXPECT_EQ(std::string(t.digest), hex)
      << t.owner << " digest type " << t.dtype;
  }
}

TEST_F(LibraryTest, DNSSECSignatures)
{
  REQUIRE_CRYPTO();
  for (const struct dv_sig &t : dv_sig) {
    std::vector<unsigned char> key  = Base64Decode(t.key);
    std::vector<unsigned char> data = Base64Decode(t.data);
    std::vector<unsigned char> sig  = Base64Decode(t.sig);

    if (!ares_dnssec_alg_supported(TestCrypto(), (unsigned char)t.alg)) {
      // like ED448 with BoringSSL
      continue;
    }
    EXPECT_EQ(t.expect, ares_dnssec_verify(TestCrypto(), (unsigned char)t.alg,
                                           key.data(), key.size(), data.data(),
                                           data.size(), sig.data(), sig.size()))
      << t.desc;
    if (t.expect == ARES_SUCCESS) {
      // a changed signature, and a signature of the wrong length
      sig[sig.size() / 2] ^= 0x01;
      EXPECT_EQ(ARES_EBADRESP,
                ares_dnssec_verify(TestCrypto(), (unsigned char)t.alg,
                                   key.data(), key.size(), data.data(),
                                   data.size(), sig.data(), sig.size()))
        << t.desc;
      EXPECT_NE(ARES_SUCCESS,
                ares_dnssec_verify(TestCrypto(), (unsigned char)t.alg,
                                   key.data(), key.size(), data.data(),
                                   data.size(), sig.data(), sig.size() - 1))
        << t.desc;
      // a key of the wrong length
      EXPECT_NE(ARES_SUCCESS,
                ares_dnssec_verify(TestCrypto(), (unsigned char)t.alg,
                                   key.data(), key.size() - 1, data.data(),
                                   data.size(), sig.data(), sig.size()))
        << t.desc;
    }
  }
  EXPECT_EQ(ARES_ENOTIMP,
            ares_dnssec_verify(TestCrypto(), 1, (const unsigned char *)"x", 1,
                               (const unsigned char *)"x", 1,
                               (const unsigned char *)"x", 1));
  EXPECT_FALSE(ares_dnssec_alg_supported(TestCrypto(), 3));   // DSA
  EXPECT_FALSE(ares_dnssec_alg_supported(TestCrypto(), 12));  // GOST
  EXPECT_FALSE(ares_dnssec_digest_supported(TestCrypto(), 3));
}

TEST_F(LibraryTest, DNSSECNsec3Hashes)
{
  REQUIRE_CRYPTO();
  static const unsigned char salt[] = { 0xaa, 0xbb, 0xcc, 0xdd };
  unsigned char              hash[DNSSEC_NSEC3_HASHLEN];
  unsigned char              expect[DNSSEC_NSEC3_HASHLEN + 1];
  unsigned char              name[DNSSEC_NAME_MAX];

  for (const struct dv_nsec3 &t : dv_nsec3) {
    ASSERT_TRUE(ParseName(t.name, name));
    ASSERT_EQ((size_t)DNSSEC_NSEC3_HASHLEN,
              ares_dnssec_b32hex_decode((const unsigned char *)t.hash,
                                        strlen(t.hash), expect,
                                        sizeof(expect)));
    ares_dnssec_name_lower(name, name);
    EXPECT_EQ(ARES_SUCCESS, ares_dnssec_nsec3_hash(
                              TestCrypto(), name, ares_dnssec_name_len(name),
                              salt, sizeof(salt), 12, hash));
    EXPECT_EQ(0, memcmp(hash, expect, sizeof(hash))) << t.name;
  }
  EXPECT_EQ(0u, ares_dnssec_b32hex_decode((const unsigned char *)"0w", 2,
                                          expect, sizeof(expect)));
  EXPECT_EQ(0u, ares_dnssec_b32hex_decode((const unsigned char *)"01", 2,
                                          expect, sizeof(expect)));
}

// Crypto functions that count the calls, for checking what c-ares does
// around them
struct FakeCrypto {
  int           verify_calls  = 0;
  ares_status_t verify_status = ARES_SUCCESS;
  int           digest_calls  = 0;
  size_t        digest_len    = 20;
  ares_status_t digest_status = ARES_SUCCESS;
};

static ares_bool_t FakeAlgSupported(unsigned char alg, void *user_data)
{
  (void)user_data;
  return (alg != 14) ? ARES_TRUE : ARES_FALSE;
}

static ares_status_t FakeVerify(unsigned char alg, const unsigned char *key,
                                size_t key_len, const unsigned char *data,
                                size_t data_len, const unsigned char *sig,
                                size_t sig_len, void *user_data)
{
  FakeCrypto *f = (FakeCrypto *)user_data;
  (void)alg;
  (void)key;
  (void)key_len;
  (void)data;
  (void)data_len;
  (void)sig;
  (void)sig_len;
  f->verify_calls++;
  return f->verify_status;
}

static ares_bool_t FakeDigestSupported(unsigned char digest_type,
                                       void         *user_data)
{
  (void)user_data;
  return (digest_type != 4) ? ARES_TRUE : ARES_FALSE;
}

static ares_status_t FakeDigest(unsigned char        digest_type,
                                const unsigned char *data, size_t data_len,
                                unsigned char *out, size_t *out_len,
                                void *user_data)
{
  FakeCrypto *f = (FakeCrypto *)user_data;
  (void)digest_type;
  (void)data;
  (void)data_len;
  f->digest_calls++;
  memset(out, 0xab, *out_len);
  *out_len = f->digest_len;
  return f->digest_status;
}

// An RSA key (RFC 3110 section 2) with an exponent of 'explen' octets and a
// modulus of 'bits' bits
static std::vector<unsigned char> RsaKey(size_t explen, size_t bits)
{
  std::vector<unsigned char> key;
  if (explen < 256) {
    key.push_back((unsigned char)explen);
  } else {
    key.push_back(0);
    key.push_back((unsigned char)(explen >> 8));
    key.push_back((unsigned char)explen);
  }
  key.insert(key.end(), explen, 0x01);
  size_t modlen = (bits + 7) / 8;
  key.push_back((unsigned char)(0xff >> ((modlen * 8) - bits)));
  key.insert(key.end(), modlen - 1, 0x55);
  return key;
}

TEST_F(LibraryTest, DNSSECCryptoChecks)
{
  FakeCrypto                 f;
  const ares_dnssec_crypto_t crypto = { FakeAlgSupported, FakeVerify,
                                        FakeDigestSupported, FakeDigest, &f };
  const unsigned char        data[] = "signed data";
  std::vector<unsigned char> sig(1024, 0x11);
  unsigned char              out[DNSSEC_DIGEST_MAX];
  unsigned char              hash[DNSSEC_NSEC3_HASHLEN];

  auto verify = [&](unsigned char alg, const std::vector<unsigned char> &key,
                    size_t siglen) {
    return ares_dnssec_verify(&crypto, alg, key.data(), key.size(), data,
                              sizeof(data), sig.data(), siglen);
  };

  // RSA: 512 to 4096 bits, 1024 bits for RSASHA512 (RFC 3110, RFC 5702),
  // an exponent of at most 8 octets, and a signature as long as the modulus
  EXPECT_EQ(ARES_SUCCESS, verify(8, RsaKey(1, 512), 64));
  EXPECT_EQ(1, f.verify_calls);
  EXPECT_EQ(ARES_SUCCESS, verify(8, RsaKey(3, 4096), 512));
  EXPECT_EQ(ARES_SUCCESS, verify(5, RsaKey(8, 1024), 128));
  EXPECT_EQ(ARES_SUCCESS, verify(10, RsaKey(3, 1024), 128));
  // the exponent length in three octets
  std::vector<unsigned char> longexp = RsaKey(3, 1024);
  longexp.erase(longexp.begin());
  longexp.insert(longexp.begin(), { 0, 0, 3 });
  EXPECT_EQ(ARES_SUCCESS, verify(8, longexp, 128));
  EXPECT_EQ(5, f.verify_calls);
  EXPECT_EQ(ARES_EFORMERR, verify(8, RsaKey(1, 511), 64));
  EXPECT_EQ(ARES_EFORMERR, verify(8, RsaKey(1, 4097), 513));
  EXPECT_EQ(ARES_EFORMERR, verify(10, RsaKey(3, 1023), 128));
  EXPECT_EQ(ARES_EFORMERR, verify(8, RsaKey(9, 1024), 128));
  EXPECT_EQ(ARES_EFORMERR, verify(8, RsaKey(1, 1024), 127));
  EXPECT_EQ(ARES_EFORMERR, verify(8, RsaKey(300, 1024), 128));
  std::vector<unsigned char> key = RsaKey(1, 1024);
  key[2]                         = 0;  // modulus with a leading zero octet
  EXPECT_EQ(ARES_EFORMERR, verify(8, key, 128));
  EXPECT_EQ(ARES_EFORMERR, verify(8, std::vector<unsigned char>(), 128));
  EXPECT_EQ(ARES_EFORMERR, verify(8, std::vector<unsigned char>(2, 0), 128));
  EXPECT_EQ(ARES_EFORMERR, verify(8, std::vector<unsigned char>(1, 5), 128));
  EXPECT_EQ(5, f.verify_calls);

  // fixed sizes for ECDSA and EdDSA (RFC 6605, RFC 8080)
  EXPECT_EQ(ARES_SUCCESS, verify(13, std::vector<unsigned char>(64, 1), 64));
  EXPECT_EQ(ARES_SUCCESS, verify(15, std::vector<unsigned char>(32, 1), 64));
  EXPECT_EQ(ARES_SUCCESS, verify(16, std::vector<unsigned char>(57, 1), 114));
  EXPECT_EQ(8, f.verify_calls);
  EXPECT_EQ(ARES_EFORMERR, verify(13, std::vector<unsigned char>(65, 1), 64));
  EXPECT_EQ(ARES_EFORMERR, verify(13, std::vector<unsigned char>(64, 1), 63));
  EXPECT_EQ(ARES_EFORMERR, verify(15, std::vector<unsigned char>(32, 1), 65));
  EXPECT_EQ(ARES_EFORMERR, verify(16, std::vector<unsigned char>(56, 1), 114));
  // not supported by the functions, and not known by c-ares
  EXPECT_EQ(ARES_ENOTIMP, verify(14, std::vector<unsigned char>(96, 1), 96));
  EXPECT_FALSE(ares_dnssec_alg_supported(&crypto, 14));
  EXPECT_EQ(ARES_ENOTIMP, verify(1, RsaKey(1, 1024), 128));
  EXPECT_FALSE(ares_dnssec_alg_supported(&crypto, 1));
  EXPECT_FALSE(ares_dnssec_alg_supported(&crypto, 12));
  EXPECT_EQ(8, f.verify_calls);

  // anything but success or out of memory means invalid
  f.verify_status = ARES_EFORMERR;
  EXPECT_EQ(ARES_EBADRESP, verify(13, std::vector<unsigned char>(64, 1), 64));
  f.verify_status = ARES_ENOMEM;
  EXPECT_EQ(ARES_ENOMEM, verify(13, std::vector<unsigned char>(64, 1), 64));

  // digests: the lengths are checked
  f.digest_len = 32;
  EXPECT_EQ(32u, ares_dnssec_digest(&crypto, 2, data, 4, data + 4, 4, out));
  EXPECT_EQ(0u, ares_dnssec_digest(&crypto, 1, data, 4, NULL, 0, out));
  f.digest_len = 20;
  EXPECT_EQ(20u, ares_dnssec_digest(&crypto, 1, data, 4, NULL, 0, out));
  f.digest_status = ARES_ENOMEM;
  EXPECT_EQ(0u, ares_dnssec_digest(&crypto, 1, data, 4, NULL, 0, out));
  f.digest_status = ARES_SUCCESS;
  EXPECT_EQ(4, f.digest_calls);
  EXPECT_EQ(0u, ares_dnssec_digest(&crypto, 4, data, 4, NULL, 0, out));
  EXPECT_EQ(0u, ares_dnssec_digest(&crypto, 3, data, 4, NULL, 0, out));
  EXPECT_FALSE(ares_dnssec_digest_supported(&crypto, 4));
  EXPECT_FALSE(ares_dnssec_digest_supported(&crypto, 3));
  EXPECT_EQ(4, f.digest_calls);

  // NSEC3: one hash plus one per iteration
  EXPECT_EQ(ARES_SUCCESS,
            ares_dnssec_nsec3_hash(&crypto, data, 4, data, 4, 5, hash));
  EXPECT_EQ(10, f.digest_calls);
  f.digest_len = 32;
  EXPECT_NE(ARES_SUCCESS,
            ares_dnssec_nsec3_hash(&crypto, data, 4, data, 4, 5, hash));
  EXPECT_EQ(11, f.digest_calls);

  // contexts need all the functions
  ares_dnssec_ctx_t   *ctx     = NULL;
  ares_dnssec_crypto_t partial = crypto;
  partial.digest               = NULL;
  EXPECT_EQ(ARES_EFORMERR, ares_dnssec_ctx_create(&partial, &ctx));
  EXPECT_EQ(ARES_EFORMERR, ares_dnssec_ctx_create(NULL, &ctx));
  EXPECT_EQ(nullptr, ctx);
}

TEST_F(LibraryTest, DNSSECAnchors)
{
  ares_dnssec_ctx_t        *ctx    = NULL;
  static const char * const good[] = {
    ". IN DS 20326 8 2 E06D44B80B8F1D39A95C0B0D7C65D084"
    "58E880409BBC683457104237C7F8EC8D",
    "example.com. 3600 IN DS 60485 5 1 ( 2BB183AF5F22588179A53B0A\n"
    "  98631FAD1A292118); comment",
    "example.com. DNSKEY 257 3 15 l02Woi0iS8Aa25FQkUd9RMzZHJpBoRQwAQEX1SxZ"
    "JA4=",
    "example.com DNSKEY 257 3 15 ( l02Woi0iS8Aa25FQkUd9RMzZ\n"
    "  HJpBoRQwAQEX1SxZJA4=)"
  };
  static const char * const bad[] = {
    "",
    ".",
    ". IN DS",
    ". IN DS 20326 8 2",
    ". IN DS 20326 8 2 E0F",
    ". IN DS 20326 8 2 XY",
    ". IN DS 70000 8 2 E0",
    ". IN A 192.0.2.1",
    "example.com. DNSKEY 257 2 15 l02Woi0iS8Aa25FQkUd9RMzZHJpBoRQwAQE=",
    "example.com. DNSKEY 257 3 15 !!!",
    "example.com. DNSKEY 257 3 15 l02Woi0iS8Aa25FQkUd9RMzZHJpBoRQwAQEX1SxZ"
    "JA4",
    "example.com. DNSKEY 257 3 15 l02W=oi0",
    "..example. DS 1 8 2 E0"
  };

  ASSERT_EQ(ARES_SUCCESS, ares_dnssec_ctx_create(&no_crypto, &ctx));
  for (const char *anchor : good) {
    EXPECT_EQ(ARES_SUCCESS, ares_dnssec_ctx_add_anchor(ctx, anchor)) << anchor;
  }
  for (const char *anchor : bad) {
    EXPECT_NE(ARES_SUCCESS, ares_dnssec_ctx_add_anchor(ctx, anchor)) << anchor;
  }
  ares_dnssec_ctx_destroy(ctx);
}

/*
 * Validation of recorded responses
 */

static const struct dv_msg *FindMsg(const struct dv_msg *table,
                                    const char *name, unsigned short qtype)
{
  if (table != nullptr) {
    for (; table->name != nullptr; table++) {
      if (table->type == qtype && ares_strcaseeq(table->name, name)) {
        return table;
      }
    }
  }
  return nullptr;
}

static const struct dv_msg *FindCaseMsg(const struct dv_case &c,
                                        const char *name, unsigned short qtype)
{
  const struct dv_msg *m = FindMsg(c.override, name, qtype);
  return m ? m : FindMsg(c.table, name, qtype);
}

// Pass a message through ares_dns_parse() and ares_dns_write(), as
// ares_query_dnssec() does
static bool RoundTrip(std::vector<unsigned char> *msg)
{
  ares_dns_record_t *dnsrec = NULL;
  unsigned char     *out    = NULL;
  size_t             len    = 0;
  if (ares_dns_parse(msg->data(), msg->size(), 0, &dnsrec) != ARES_SUCCESS) {
    return false;
  }
  ares_status_t status = ares_dns_write(dnsrec, &out, &len);
  ares_dns_record_destroy(dnsrec);
  if (status != ARES_SUCCESS) {
    return false;
  }
  msg->assign(out, out + len);
  ares_free_string(out);
  return true;
}

struct DNSSECResult {
  ares_dnssec_status_t status;
  int                  rcode;
  size_t               count;
  std::string          reason;
};

static DNSSECResult RunCase(const struct dv_case &c, bool roundtrip)
{
  ares_dnssec_ctx_t *ctx = NULL;
  ares_dnssec_req_t *req = NULL;
  DNSSECResult       res = { ARES_DNSSEC_INDETERMINATE, -1, 0, "" };
  int                rounds;

  EXPECT_EQ(ARES_SUCCESS, ares_dnssec_ctx_create(TestCrypto(), &ctx));
  if (ctx == NULL) {
    return res;
  }
  if (c.anchors != nullptr) {
    ares_dnssec_ctx_clear_anchors(ctx);
    for (const char * const *a = c.anchors; *a; a++) {
      EXPECT_EQ(ARES_SUCCESS, ares_dnssec_ctx_add_anchor(ctx, *a)) << *a;
    }
  }
  ares_dnssec_ctx_set_time(ctx, (time_t)c.now);
  ares_dnssec_ctx_set_flags(ctx, c.flags);
  EXPECT_EQ(ARES_SUCCESS, ares_dnssec_req_create(
                            ctx, c.qname, (unsigned short)c.qtype, &req));
  if (req == NULL) {
    ares_dnssec_ctx_destroy(ctx);
    return res;
  }

  for (rounds = 0; rounds < 100; rounds++) {
    ares_bool_t    done = ARES_FALSE;
    char           name[ARES_DNSSEC_NAME_STRLEN];
    unsigned short qtype;

    EXPECT_EQ(ARES_SUCCESS, ares_dnssec_req_run(req, &done));
    if (done) {
      break;
    }
    while (ares_dnssec_ctx_next_query(ctx, name, sizeof(name), &qtype)) {
      const struct dv_msg *m = FindCaseMsg(c, name, qtype);
      if (m == nullptr) {
        EXPECT_EQ(ARES_SUCCESS, ares_dnssec_ctx_add_failure(ctx, name, qtype));
        continue;
      }
      std::vector<unsigned char> msg = Pieces(m->msg);
      if (roundtrip && !RoundTrip(&msg)) {
        EXPECT_EQ(ARES_SUCCESS, ares_dnssec_ctx_add_failure(ctx, name, qtype));
        continue;
      }
      EXPECT_EQ(ARES_SUCCESS, ares_dnssec_ctx_add_response(
                                ctx, name, qtype, msg.data(), msg.size()));
    }
  }
  EXPECT_LT(rounds, 100) << c.desc << ": does not finish";

  res.status = ares_dnssec_req_status(req);
  res.rcode  = ares_dnssec_req_rcode(req);
  res.count  = ares_dnssec_req_count(req);
  if (ares_dnssec_req_reason(req) != nullptr) {
    res.reason = ares_dnssec_req_reason(req);
  }
  if (res.status == ARES_DNSSEC_SECURE) {
    EXPECT_EQ(nullptr, ares_dnssec_req_reason(req)) << c.desc;
  } else {
    EXPECT_NE(nullptr, ares_dnssec_req_reason(req)) << c.desc;
  }
  if (res.count) {
    const unsigned char *rdata;
    size_t               rdlen;
    EXPECT_TRUE(ares_dnssec_req_rdata(req, res.count - 1, &rdata, &rdlen));
    EXPECT_FALSE(ares_dnssec_req_rdata(req, res.count, &rdata, &rdlen));
  }

  ares_dnssec_req_destroy(req);
  ares_dnssec_ctx_destroy(ctx);
  return res;
}

static void CheckCase(const struct dv_case &c, const DNSSECResult &res)
{
  EXPECT_EQ(c.status, res.status)
    << c.desc << ": " << ares_dnssec_status_str(res.status) << ", "
    << res.reason;
  if (c.rcode >= 0) {
    EXPECT_EQ(c.rcode, res.rcode) << c.desc;
  }
  if (c.count >= 0) {
    EXPECT_EQ((size_t)c.count, res.count) << c.desc;
  }
}

TEST_F(LibraryTest, DNSSECVectors)
{
  REQUIRE_CRYPTO();
  for (const struct dv_case &c : dv_cases) {
    CheckCase(c, RunCase(c, false));
  }
}

// The same, with the responses parsed and written again by c-ares first
TEST_F(LibraryTest, DNSSECVectorsRoundTrip)
{
  REQUIRE_CRYPTO();
  for (const struct dv_case &c : dv_cases) {
    CheckCase(c, RunCase(c, true));
  }
}

TEST_F(LibraryTest, DNSSECRequests)
{
  ares_dnssec_ctx_t   *ctx = NULL;
  ares_dnssec_req_t   *req = NULL;
  char                 name[ARES_DNSSEC_NAME_STRLEN];
  unsigned short       qtype;
  ares_bool_t          done = ARES_FALSE;
  const struct dv_msg *m;

  ASSERT_EQ(ARES_SUCCESS, ares_dnssec_ctx_create(&no_crypto, &ctx));
  EXPECT_EQ(ARES_EFORMERR,
            ares_dnssec_req_create(ctx, "example.com", 255, &req));
  EXPECT_EQ(ARES_EFORMERR, ares_dnssec_req_create(ctx, "a..b", 1, &req));
  EXPECT_EQ(ARES_EFORMERR, ares_dnssec_ctx_add_failure(ctx, "example.com.", 1));

  // a response to another question is a failed lookup
  ASSERT_EQ(ARES_SUCCESS,
            ares_dnssec_req_create(ctx, "www.nsec.test.", 1, &req));
  ares_dnssec_ctx_clear_anchors(ctx);
  EXPECT_EQ(ARES_SUCCESS, ares_dnssec_req_run(req, &done));
  EXPECT_FALSE(done);
  EXPECT_EQ(1u, ares_dnssec_ctx_pending(ctx));
  EXPECT_TRUE(ares_dnssec_ctx_next_query(ctx, name, sizeof(name), &qtype));
  EXPECT_STREQ("www.nsec.test.", name);
  EXPECT_EQ(1, qtype);
  EXPECT_FALSE(ares_dnssec_ctx_next_query(ctx, name, sizeof(name), &qtype));
  m = FindMsg(dv_bind, "www.nsec.test.", 16);
  ASSERT_NE(nullptr, m);
  std::vector<unsigned char> msg = Pieces(m->msg);
  EXPECT_EQ(ARES_SUCCESS, ares_dnssec_ctx_add_response(ctx, "www.nsec.test.", 1,
                                                       msg.data(), msg.size()));
  EXPECT_EQ(0u, ares_dnssec_ctx_pending(ctx));
  EXPECT_EQ(ARES_SUCCESS, ares_dnssec_req_run(req, &done));
  EXPECT_TRUE(done);
  EXPECT_EQ(ARES_DNSSEC_INDETERMINATE, ares_dnssec_req_status(req));
  EXPECT_EQ(0u, ares_dnssec_req_count(req));

  ares_dnssec_req_destroy(req);
  ares_dnssec_ctx_destroy(ctx);
}

/*
 * ares_query_dnssec() with a mock server answering with the recorded
 * responses
 */

// The test crypto functions for ares_set_dnssec_crypto_functions(), NULL
// when there are none
static const struct ares_dnssec_crypto_functions *TestCryptoFuncs()
{
#  ifdef CARES_TEST_OPENSSL
  static const struct ares_dnssec_crypto_functions funcs = {
    1, TestAlgSupported, TestVerify, TestDigestSupported, TestDigest
  };
  return &funcs;
#  else
  return nullptr;
#  endif
}

class DNSSECMockBase
  : public MockChannelOptsTest,
    public ::testing::WithParamInterface<std::pair<int, bool>> {
public:
  explicit DNSSECMockBase(bool cache)
    : MockChannelOptsTest(1, GetParam().first, GetParam().second, false,
                          FillOptions(&opts_, cache),
                          ARES_OPT_FLAGS | (cache ? ARES_OPT_QUERY_CACHE : 0))
  {
    if (TestCryptoFuncs() != nullptr) {
      EXPECT_EQ(ARES_SUCCESS, ares_set_dnssec_crypto_functions(
                                channel_, TestCryptoFuncs(), nullptr));
    }
  }

  static struct ares_options *FillOptions(struct ares_options *opts, bool cache)
  {
    // The recorded responses have lowercase question names, so no DNS 0x20
    memset(opts, 0, sizeof(*opts));
    opts->flags          = ARES_FLAG_EDNS;
    opts->qcache_max_ttl = cache ? 3600 : 0;
    return opts;
  }

  // Answer queries from the tables of a test case, with SERVFAIL for queries
  // without a response
  void ServeCase(const struct dv_case &c)
  {
    ON_CALL(server_, OnRequest(_, _))
      .WillByDefault([this, &c](const std::string &name, int type) {
        std::string fqdn = name;
        if (fqdn.empty() || fqdn[fqdn.size() - 1] != '.') {
          fqdn += '.';
        }
        const struct dv_msg *m =
          FindCaseMsg(c, fqdn.c_str(), (unsigned short)type);
        if (m != nullptr) {
          server_.SetReplyData(Pieces(m->msg));
        } else {
          servfail_.reset(new DNSPacket());
          servfail_->set_response().set_rcode(SERVFAIL).add_question(
            new DNSQuestion(name, type));
          server_.SetReply(servfail_.get());
        }
      });
  }

  void SetCaseParams(const struct dv_case &c)
  {
    std::string anchors;
    if (c.anchors != nullptr) {
      for (const char * const *a = c.anchors; *a; a++) {
        anchors += *a;
        anchors += "\n";
      }
    }
    EXPECT_EQ(ARES_SUCCESS,
              ares_dnssec_set_test_params(
                channel_, c.anchors != nullptr ? anchors.c_str() : NULL,
                (time_t)c.now, c.flags));
  }

private:
  struct ares_options        opts_;
  std::unique_ptr<DNSPacket> servfail_;
};

class DNSSECMockTest : public DNSSECMockBase {
public:
  DNSSECMockTest() : DNSSECMockBase(false)
  {
  }
};

// With the query cache on
class DNSSECCacheMockTest : public DNSSECMockBase {
public:
  DNSSECCacheMockTest() : DNSSECMockBase(true)
  {
  }
};

struct DNSSECQueryResult {
  DNSSECQueryResult() : done(false), status(ARES_SUCCESS), timeouts(0)
  {
  }

  ~DNSSECQueryResult()
  {
    ares_dns_record_destroy(dnsrec);
  }

  bool               done;
  ares_status_t      status;
  size_t             timeouts;
  ares_dns_record_t *dnsrec = nullptr;
};

static void DNSSECQueryCallback(void *arg, ares_status_t status,
                                size_t                   timeouts,
                                const ares_dns_record_t *dnsrec)
{
  DNSSECQueryResult *result = (DNSSECQueryResult *)arg;
  EXPECT_FALSE(result->done);
  result->done     = true;
  result->status   = status;
  result->timeouts = timeouts;
  if (dnsrec != nullptr) {
    result->dnsrec = ares_dns_record_duplicate(dnsrec);
  }
}

// The validation result the record tells
static ares_dnssec_status_t RecordStatus(const ares_dns_record_t *dnsrec)
{
  if (ares_dns_record_get_rcode(dnsrec) != ARES_RCODE_SERVFAIL) {
    return (ares_dns_record_get_flags(dnsrec) & ARES_FLAG_AD)
             ? ARES_DNSSEC_SECURE
             : ARES_DNSSEC_INSECURE;
  }
  for (size_t i = 0;
       i < ares_dns_record_rr_cnt(dnsrec, ARES_SECTION_ADDITIONAL); i++) {
    const ares_dns_rr_t *rr =
      ares_dns_record_rr_get_const(dnsrec, ARES_SECTION_ADDITIONAL, i);
    const unsigned char *val = NULL;
    size_t               len = 0;
    if (ares_dns_rr_get_type(rr) == ARES_REC_TYPE_OPT &&
        ares_dns_rr_get_opt_byid(rr, ARES_RR_OPT_OPTIONS,
                                 ARES_OPT_PARAM_EXTENDED_DNS_ERROR, &val,
                                 &len) &&
        len >= 2) {
      return (val[0] == 0 && val[1] == 6) ? ARES_DNSSEC_BOGUS
                                          : ARES_DNSSEC_INDETERMINATE;
    }
  }
  return ARES_DNSSEC_INDETERMINATE;
}

static size_t RecordCount(const ares_dns_record_t *dnsrec, int qtype)
{
  size_t n = 0;
  for (size_t i = 0; i < ares_dns_record_rr_cnt(dnsrec, ARES_SECTION_ANSWER);
       i++) {
    const ares_dns_rr_t *rr =
      ares_dns_record_rr_get_const(dnsrec, ARES_SECTION_ANSWER, i);
    if ((int)ares_dns_rr_get_type(rr) == qtype) {
      n++;
    }
  }
  return n;
}

TEST_P(DNSSECMockTest, Vectors)
{
  REQUIRE_CRYPTO();
  for (const struct dv_case &c : dv_cases) {
    DNSSECQueryResult result;
    ServeCase(c);
    SetCaseParams(c);
    EXPECT_EQ(ARES_SUCCESS,
              ares_query_dnssec(channel_, c.qname, (ares_dns_rec_type_t)c.qtype,
                                DNSSECQueryCallback, &result));
    Process();
    ASSERT_TRUE(result.done) << c.desc;
    ASSERT_NE(nullptr, result.dnsrec) << c.desc;
    EXPECT_EQ(c.status, RecordStatus(result.dnsrec)) << c.desc;
    if (c.status == ARES_DNSSEC_SECURE || c.status == ARES_DNSSEC_INSECURE) {
      if (c.rcode >= 0) {
        EXPECT_EQ(c.rcode, (int)ares_dns_record_get_rcode(result.dnsrec))
          << c.desc;
      }
      // with CNAME, the links followed are CNAME records too
      if (c.count >= 0 && c.qtype != ARES_REC_TYPE_CNAME) {
        EXPECT_EQ((size_t)c.count, RecordCount(result.dnsrec, c.qtype))
          << c.desc;
      }
    } else {
      EXPECT_EQ(ARES_ESERVFAIL, result.status) << c.desc;
    }
    testing::Mock::VerifyAndClearExpectations(&server_);
  }
}

static const struct dv_case &FindCase(const char *desc)
{
  for (const struct dv_case &c : dv_cases) {
    if (strcmp(c.desc, desc) == 0) {
      return c;
    }
  }
  ADD_FAILURE() << "no test case " << desc;
  return dv_cases[0];
}

// Validate the answer to a test case with ares_query_dnssec()
static void QueryCase(DNSSECMockBase *t, ares_channel_t *channel,
                      const struct dv_case &c, DNSSECQueryResult *result)
{
  t->ServeCase(c);
  t->SetCaseParams(c);
  EXPECT_EQ(ARES_SUCCESS,
            ares_query_dnssec(channel, c.qname, (ares_dns_rec_type_t)c.qtype,
                              DNSSECQueryCallback, result));
  t->Process();
  EXPECT_TRUE(result->done);
}

static std::string RRName(const ares_dns_record_t *dnsrec, size_t idx)
{
  const ares_dns_rr_t *rr =
    ares_dns_record_rr_get_const(dnsrec, ARES_SECTION_ANSWER, idx);
  return rr ? ares_dns_rr_get_name(rr) : "";
}

static ares_dns_rec_type_t RRType(const ares_dns_record_t *dnsrec, size_t idx)
{
  const ares_dns_rr_t *rr =
    ares_dns_record_rr_get_const(dnsrec, ARES_SECTION_ANSWER, idx);
  return rr ? ares_dns_rr_get_type(rr) : ARES_REC_TYPE_RAW_RR;
}

TEST_P(DNSSECMockTest, Secure)
{
  REQUIRE_CRYPTO();
  DNSSECQueryResult result;
  QueryCase(this, channel_, FindCase("BIND answer"), &result);
  EXPECT_EQ(ARES_SUCCESS, result.status);
  ASSERT_NE(nullptr, result.dnsrec);
  EXPECT_TRUE(ares_dns_record_get_flags(result.dnsrec) & ARES_FLAG_AD);
  EXPECT_TRUE(ares_dns_record_get_flags(result.dnsrec) & ARES_FLAG_QR);
  EXPECT_EQ(ARES_RCODE_NOERROR, ares_dns_record_get_rcode(result.dnsrec));
  ASSERT_EQ(1u, ares_dns_record_query_cnt(result.dnsrec));
  ASSERT_EQ(1u, ares_dns_record_rr_cnt(result.dnsrec, ARES_SECTION_ANSWER));
  EXPECT_EQ(ARES_REC_TYPE_A, RRType(result.dnsrec, 0));
  EXPECT_EQ("www.nsec.test", RRName(result.dnsrec, 0));
  // only validated data, no signatures, no authority or additional records
  EXPECT_EQ(0u, ares_dns_record_rr_cnt(result.dnsrec, ARES_SECTION_AUTHORITY));
  EXPECT_EQ(0u, ares_dns_record_rr_cnt(result.dnsrec, ARES_SECTION_ADDITIONAL));
}

TEST_P(DNSSECMockTest, SecureCNAME)
{
  REQUIRE_CRYPTO();
  DNSSECQueryResult result;
  QueryCase(this, channel_, FindCase("BIND CNAME"), &result);
  EXPECT_EQ(ARES_SUCCESS, result.status);
  ASSERT_NE(nullptr, result.dnsrec);
  EXPECT_TRUE(ares_dns_record_get_flags(result.dnsrec) & ARES_FLAG_AD);
  ASSERT_EQ(2u, ares_dns_record_rr_cnt(result.dnsrec, ARES_SECTION_ANSWER));
  EXPECT_EQ(ARES_REC_TYPE_CNAME, RRType(result.dnsrec, 0));
  EXPECT_EQ("alias.nsec.test", RRName(result.dnsrec, 0));
  const ares_dns_rr_t *rr =
    ares_dns_record_rr_get_const(result.dnsrec, ARES_SECTION_ANSWER, 0);
  EXPECT_EQ(RRName(result.dnsrec, 1),
            std::string(ares_dns_rr_get_str(rr, ARES_RR_CNAME_CNAME)));
  EXPECT_EQ(ARES_REC_TYPE_A, RRType(result.dnsrec, 1));

  // A real one, a chain to another zone
  DNSSECQueryResult result2;
  QueryCase(this, channel_, FindCase("real CNAME"), &result2);
  EXPECT_EQ(ARES_SUCCESS, result2.status);
  ASSERT_NE(nullptr, result2.dnsrec);
  EXPECT_TRUE(ares_dns_record_get_flags(result2.dnsrec) & ARES_FLAG_AD);
  EXPECT_EQ(ARES_REC_TYPE_CNAME, RRType(result2.dnsrec, 0));
  EXPECT_EQ("www.huque.com", RRName(result2.dnsrec, 0));
  size_t n = ares_dns_record_rr_cnt(result2.dnsrec, ARES_SECTION_ANSWER);
  ASSERT_GE(n, 2u);
  EXPECT_EQ(ARES_REC_TYPE_AAAA, RRType(result2.dnsrec, n - 1));
}

TEST_P(DNSSECMockTest, SecureNXDOMAIN)
{
  REQUIRE_CRYPTO();
  DNSSECQueryResult result;
  QueryCase(this, channel_, FindCase("BIND NXDOMAIN"), &result);
  EXPECT_EQ(ARES_ENOTFOUND, result.status);
  ASSERT_NE(nullptr, result.dnsrec);
  EXPECT_TRUE(ares_dns_record_get_flags(result.dnsrec) & ARES_FLAG_AD);
  EXPECT_EQ(ARES_RCODE_NXDOMAIN, ares_dns_record_get_rcode(result.dnsrec));
  EXPECT_EQ(0u, ares_dns_record_rr_cnt(result.dnsrec, ARES_SECTION_ANSWER));

  DNSSECQueryResult result2;
  QueryCase(this, channel_, FindCase("BIND NODATA"), &result2);
  EXPECT_EQ(ARES_ENODATA, result2.status);
  ASSERT_NE(nullptr, result2.dnsrec);
  EXPECT_TRUE(ares_dns_record_get_flags(result2.dnsrec) & ARES_FLAG_AD);
  EXPECT_EQ(ARES_RCODE_NOERROR, ares_dns_record_get_rcode(result2.dnsrec));
}

TEST_P(DNSSECMockTest, Insecure)
{
  REQUIRE_CRYPTO();
  DNSSECQueryResult result;
  QueryCase(this, channel_, FindCase("BIND unsigned zone"), &result);
  EXPECT_EQ(ARES_SUCCESS, result.status);
  ASSERT_NE(nullptr, result.dnsrec);
  EXPECT_FALSE(ares_dns_record_get_flags(result.dnsrec) & ARES_FLAG_AD);
  EXPECT_EQ(ARES_RCODE_NOERROR, ares_dns_record_get_rcode(result.dnsrec));
  ASSERT_EQ(1u, ares_dns_record_rr_cnt(result.dnsrec, ARES_SECTION_ANSWER));
  EXPECT_EQ(ARES_REC_TYPE_A, RRType(result.dnsrec, 0));
}

TEST_P(DNSSECMockTest, Bogus)
{
  REQUIRE_CRYPTO();
  DNSSECQueryResult result;
  QueryCase(this, channel_, FindCase("BIND attack: changed address"), &result);
  EXPECT_EQ(ARES_ESERVFAIL, result.status);
  ASSERT_NE(nullptr, result.dnsrec);
  EXPECT_FALSE(ares_dns_record_get_flags(result.dnsrec) & ARES_FLAG_AD);
  EXPECT_EQ(ARES_RCODE_SERVFAIL, ares_dns_record_get_rcode(result.dnsrec));
  EXPECT_EQ(0u, ares_dns_record_rr_cnt(result.dnsrec, ARES_SECTION_ANSWER));
  ASSERT_EQ(1u, ares_dns_record_rr_cnt(result.dnsrec, ARES_SECTION_ADDITIONAL));
  const ares_dns_rr_t *opt =
    ares_dns_record_rr_get_const(result.dnsrec, ARES_SECTION_ADDITIONAL, 0);
  const unsigned char *val = NULL;
  size_t               len = 0;
  ASSERT_TRUE(ares_dns_rr_get_opt_byid(
    opt, ARES_RR_OPT_OPTIONS, ARES_OPT_PARAM_EXTENDED_DNS_ERROR, &val, &len));
  ASSERT_GT(len, 2u);
  // RFC 8914 4.7: DNSSEC Bogus, and the reason as text
  EXPECT_EQ(0, val[0]);
  EXPECT_EQ(6, val[1]);
  std::string text((const char *)val + 2, len - 2);
  EXPECT_EQ(0u, text.find("RRSIG for www.nsec.test. A by key ")) << text;
  EXPECT_NE(std::string::npos, text.find(" does not verify")) << text;
}

TEST_P(DNSSECMockTest, Timeout)
{
  REQUIRE_CRYPTO();
  DNSSECQueryResult result;
  // no response to anything
  ON_CALL(server_, OnRequest(_, _))
    .WillByDefault(SetReplyData(&server_, std::vector<byte>()));
  EXPECT_EQ(ARES_SUCCESS,
            ares_query_dnssec(channel_, "www.example.com", ARES_REC_TYPE_A,
                              DNSSECQueryCallback, &result));
  Process();
  EXPECT_TRUE(result.done);
  EXPECT_EQ(ARES_ESERVFAIL, result.status);
  EXPECT_GT(result.timeouts, 0u);
  ASSERT_NE(nullptr, result.dnsrec);
  EXPECT_EQ(ARES_DNSSEC_INDETERMINATE, RecordStatus(result.dnsrec));
}

TEST_P(DNSSECMockTest, Cancel)
{
  REQUIRE_CRYPTO();
  DNSSECQueryResult result;
  ServeCase(FindCase("BIND answer"));
  SetCaseParams(FindCase("BIND answer"));
  EXPECT_EQ(ARES_SUCCESS,
            ares_query_dnssec(channel_, "www.nsec.test", ARES_REC_TYPE_A,
                              DNSSECQueryCallback, &result));
  EXPECT_FALSE(result.done);
  ares_cancel(channel_);
  EXPECT_TRUE(result.done);
  EXPECT_EQ(ARES_ECANCELLED, result.status);
  EXPECT_EQ(nullptr, result.dnsrec);
  Process();
}

TEST_P(DNSSECMockTest, Misuse)
{
  DNSSECQueryResult                         result;
  FakeCrypto                                f;
  const struct ares_dnssec_crypto_functions fake = {
    1, FakeAlgSupported, FakeVerify, FakeDigestSupported, FakeDigest
  };
  EXPECT_EQ(ARES_SUCCESS,
            ares_set_dnssec_crypto_functions(channel_, &fake, &f));
  EXPECT_EQ(ARES_EFORMERR,
            ares_query_dnssec(nullptr, "www.example.com", ARES_REC_TYPE_A,
                              DNSSECQueryCallback, &result));
  EXPECT_EQ(ARES_EFORMERR,
            ares_query_dnssec(channel_, "www.example.com", ARES_REC_TYPE_A,
                              nullptr, &result));
  EXPECT_FALSE(result.done);

  const struct {
    const char         *name;
    ares_dns_rec_type_t type;
  } bad[] = {
    { nullptr,           ARES_REC_TYPE_A      },
    { "a..b",            ARES_REC_TYPE_A      },
    { "www.example.com", ARES_REC_TYPE_ANY    },
    { "www.example.com", ARES_REC_TYPE_OPT    },
    { "www.example.com", ARES_REC_TYPE_RRSIG  },
    { "www.example.com", ARES_REC_TYPE_RAW_RR }
  };

  for (const auto &b : bad) {
    DNSSECQueryResult r;
    EXPECT_EQ(ARES_EFORMERR, ares_query_dnssec(channel_, b.name, b.type,
                                               DNSSECQueryCallback, &r));
    EXPECT_TRUE(r.done);
    EXPECT_EQ(ARES_EFORMERR, r.status);
    EXPECT_EQ(nullptr, r.dnsrec);
  }

  // without crypto functions
  EXPECT_EQ(ARES_SUCCESS,
            ares_set_dnssec_crypto_functions(channel_, nullptr, nullptr));
  DNSSECQueryResult r;
  EXPECT_EQ(ARES_ENOTIMP,
            ares_query_dnssec(channel_, "www.example.com", ARES_REC_TYPE_A,
                              DNSSECQueryCallback, &r));
  EXPECT_TRUE(r.done);
  EXPECT_EQ(ARES_ENOTIMP, r.status);
  EXPECT_EQ(nullptr, r.dnsrec);
}

INSTANTIATE_TEST_SUITE_P(AddressFamilies, DNSSECMockTest,
                         ::testing::ValuesIn(ares::test::families_modes),
                         PrintFamilyMode);

TEST_F(DefaultChannelTest, DNSSECCryptoFunctions)
{
  FakeCrypto                          f;
  struct ares_dnssec_crypto_functions funcs = { 1, FakeAlgSupported, FakeVerify,
                                                FakeDigestSupported,
                                                FakeDigest };
  struct ares_dnssec_crypto_functions bad;
  ares_channel_t                     *dup = nullptr;
  DNSSECQueryResult                   r1;
  DNSSECQueryResult                   r2;
  DNSSECQueryResult                   r3;

  EXPECT_EQ(ARES_EFORMERR,
            ares_set_dnssec_crypto_functions(nullptr, &funcs, &f));
  bad         = funcs;
  bad.version = 0;
  EXPECT_EQ(ARES_EFORMERR,
            ares_set_dnssec_crypto_functions(channel_, &bad, &f));
  bad.version = 2;
  EXPECT_EQ(ARES_EFORMERR,
            ares_set_dnssec_crypto_functions(channel_, &bad, &f));
  bad        = funcs;
  bad.verify = nullptr;
  EXPECT_EQ(ARES_EFORMERR,
            ares_set_dnssec_crypto_functions(channel_, &bad, &f));
  // the algorithms and digest types every validator must support
  bad               = funcs;
  bad.alg_supported = NoAlgSupported;
  EXPECT_EQ(ARES_EFORMERR,
            ares_set_dnssec_crypto_functions(channel_, &bad, &f));
  bad                  = funcs;
  bad.digest_supported = NoAlgSupported;
  EXPECT_EQ(ARES_EFORMERR,
            ares_set_dnssec_crypto_functions(channel_, &bad, &f));
  // nothing was set
  EXPECT_EQ(ARES_ENOTIMP, ares_query_dnssec(channel_, "a..b", ARES_REC_TYPE_A,
                                            DNSSECQueryCallback, &r1));

  // set, and copied by ares_dup(): the name is checked now
  EXPECT_EQ(ARES_SUCCESS,
            ares_set_dnssec_crypto_functions(channel_, &funcs, &f));
  ASSERT_EQ(ARES_SUCCESS, ares_dup(&dup, channel_));
  EXPECT_EQ(ARES_EFORMERR, ares_query_dnssec(dup, "a..b", ARES_REC_TYPE_A,
                                             DNSSECQueryCallback, &r2));
  ares_destroy(dup);

  // removed
  EXPECT_EQ(ARES_SUCCESS,
            ares_set_dnssec_crypto_functions(channel_, nullptr, nullptr));
  EXPECT_EQ(ARES_ENOTIMP, ares_query_dnssec(channel_, "a..b", ARES_REC_TYPE_A,
                                            DNSSECQueryCallback, &r3));
}

// The queries of a second validation are answered from the cache
TEST_P(DNSSECCacheMockTest, Cached)
{
  REQUIRE_CRYPTO();
  const struct dv_case &c        = FindCase("BIND answer");
  size_t                requests = 0;

  SetCaseParams(c);
  EXPECT_CALL(server_, OnRequest(_, _))
    .WillRepeatedly([this, &c, &requests](const std::string &name, int type) {
      std::string          fqdn = name + ".";
      const struct dv_msg *m =
        FindCaseMsg(c, fqdn.c_str(), (unsigned short)type);
      requests++;
      server_.SetReplyData(m ? Pieces(m->msg) : std::vector<byte>());
    });

  DNSSECQueryResult result1;
  EXPECT_EQ(ARES_SUCCESS,
            ares_query_dnssec(channel_, c.qname, (ares_dns_rec_type_t)c.qtype,
                              DNSSECQueryCallback, &result1));
  Process();
  EXPECT_TRUE(result1.done);
  ASSERT_NE(nullptr, result1.dnsrec);
  EXPECT_EQ(ARES_DNSSEC_SECURE, RecordStatus(result1.dnsrec));
  size_t first = requests;
  EXPECT_GT(first, 0u);

  DNSSECQueryResult result2;
  EXPECT_EQ(ARES_SUCCESS,
            ares_query_dnssec(channel_, c.qname, (ares_dns_rec_type_t)c.qtype,
                              DNSSECQueryCallback, &result2));
  Process();
  EXPECT_TRUE(result2.done);
  ASSERT_NE(nullptr, result2.dnsrec);
  EXPECT_EQ(ARES_DNSSEC_SECURE, RecordStatus(result2.dnsrec));
  EXPECT_EQ(first, requests);
}

INSTANTIATE_TEST_SUITE_P(AddressFamilies, DNSSECCacheMockTest,
                         ::testing::ValuesIn(ares::test::families_modes),
                         PrintFamilyMode);

}  // namespace test
}  // namespace ares

#endif
